# Generated by Django 4.1.6 on 2023-02-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LetsfitAuto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='number',
            new_name='phonenumber',
        ),
    ]
