# Generated by Django 4.1.6 on 2023-02-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LetsfitAuto', '0002_rename_number_customer_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phonenumber',
            new_name='mobile_number',
        ),
    ]
