# Generated by Django 4.1.6 on 2023-02-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsfitAuto', '0003_rename_phonenumber_customer_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
